asset_url:          'http://widget.icrm.icfdev.ru/widget'
system_logger_url:  'http://icrm.icfdev.ru/logger'
system_chat_url:    'http://icrm.icfdev.ru/chat'
faye_url:           'http://icrm.icfdev.ru:8808/faye'
